config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
    registrations: 'users/registrations'
  }
  resources :assemblies
  resources :wines
  resources :strains
  root 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :assemblies, dependent: :destroy
    has_many :strains, through: :assemblies, dependent: :destroy
    accepts_nested_attributes_for :assemblies, allow_destroy: true

    validates_associated :assemblies
    validates_associated :strains

    def build_strains
        a = Assembly.references(:wines).where(wine_id: id)
        
        a.map{|s| "#{s.nameStrain} (#{s.proportion}%)" }.join(", ")
    end

    
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /wines or /wines.json
  def index
    @wines = Wine.all.order(age: :asc)
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :age,:score, assemblies_attributes: [:id, :strain_id,:proportion ,:_destroy])
      
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_assembly_fields.html.erb
<div class="nested-fields">
<div class="fields">
    <%= f.select :strain_id, Strain.all.map{|s|[s.name, s.id]}%>
    <%= f.label :proportion%>
    <%= f.number_field :proportion%>
    
    <%= link_to_remove_association "Remove Strain", f%>
</div>
</div>

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :age %>
    <%= form.number_field  :age%>
  </div>
  <div class="field">
    <%= form.label :score %>
    <%= form.number_field  :score , in: 0..100%>
  </div>
  <div class="field">
    <%= form.label :Strains %>
      <%= form.fields_for :assemblies do |s| %>
    <%= render 'assembly_fields', f: s %>
    <% end %>
    <div class="links form-inline">
      <%= link_to_add_association 'add strain', form, :assemblies %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Score</th>
      <th>Strains</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<%if current_user.role_id == 1 || current_user.role_id == 3%>
  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.age %></td>
        <td><%= wine.score %></td>
        <td><%= wine.build_strains%></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role_id == 1 %>
  <%= link_to 'New Wine', new_wine_path %>
<% end %>

<%else%>
 <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <% end %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>