config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {
    registrations: 'users/registrations'
  }
  resources :assemblies
  resources :wines
  resources :strains
  root 'wines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
  accepts_nested_attributes_for :strain, allow_destroy: true

  def nameStrain
    s =  Strain.where(id: strain_id).pluck :name
    s.first
  end
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  before_action :set_assembly, only: %i[ show edit update destroy ]

  # GET /assemblies or /assemblies.json
  def index
    @assemblies = Assembly.all
  end

  # GET /assemblies/1 or /assemblies/1.json
  def show
  end

  # GET /assemblies/new
  def new
    @assembly = Assembly.new
  end

  # GET /assemblies/1/edit
  def edit
  end

  # POST /assemblies or /assemblies.json
  def create
    @assembly = Assembly.new(assembly_params)

    respond_to do |format|
      if @assembly.save
        format.html { redirect_to @assembly, notice: "Assembly was successfully created." }
        format.json { render :show, status: :created, location: @assembly }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblies/1 or /assemblies/1.json
  def update
    respond_to do |format|
      if @assembly.update(assembly_params)
        format.html { redirect_to @assembly, notice: "Assembly was successfully updated." }
        format.json { render :show, status: :ok, location: @assembly }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1 or /assemblies/1.json
  def destroy
    @assembly.destroy
    respond_to do |format|
      format.html { redirect_to assemblies_url, notice: "Assembly was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assembly
      @assembly = Assembly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assembly_params
      params.require(:assembly).permit(:wine_id, :strain_id)
    end
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/views/assemblies/_form.html.erb
<%= form_with(model: assembly) do |form| %>
  <% if assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
        <% assembly.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_id %>
    <%= form.text_field :wine_id %>
  </div>

  <div class="field">
    <%= form.label :strain_id %>
    <%= form.text_field :strain_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assemblies/edit.html.erb
<h1>Editing Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

app/views/assemblies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assemblies</h1>

<table>
  <thead>
    <tr>
      <th>Wine</th>
      <th>Strain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblies.each do |assembly| %>
      <tr>
        <td><%= assembly.wine_id %></td>
        <td><%= assembly.strain_id %></td>
        <td><%= link_to 'Show', assembly %></td>
        <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
        <td><%= link_to 'Destroy', assembly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assembly', new_assembly_path %>

app/views/assemblies/new.html.erb
<h1>New Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Back', assemblies_path %>

app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine:</strong>
  <%= @assembly.wine_id %>
</p>

<p>
  <strong>Strain:</strong>
  <%= @assembly.strain_id %>
</p>

<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>